language: java
jdk:
  - oraclejdk8
before_script:
  - sudo add-apt-repository "deb http://www.rabbitmq.com/debian/ testing main"
  - wget https://www.rabbitmq.com/rabbitmq-signing-key-public.asc && sudo apt-key add rabbitmq-signing-key-public.asc
  - sudo apt-get update -qq
  - sudo apt-get install rabbitmq-server
after_success:
  - mvn -Drod.build.env=travis clean install jacoco:report coveralls:report
