info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    build.version: ${project.version}
  app:
    name: ROD
    description: Robot On Duty
    version: ${project.version}

management:
  health:
    rabbit:
      enabled: false

endpoints:
  health:
    enabled: yes
    sensitive: true
  jmx:
    enabled: true
    domain: rod

logging:
  file: rod.log
  
---
 
 spring:
   profiles: messaging
 server:
   port: 8080
 rod:
   controller:
     message: true
   supervisor: true
 
---
 
 spring:
   profiles: control
 server:
  port: 8090
 rod:
   controller:
     message: false
   supervisor: true